branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\Strawberry538
  #- C:\Strawberry -> appveyor.yml

install:
  - set ST=C:\Strawberry538
  - if exist %ST% del /Q %ST%
  - if not exist %ST% appveyor-retry choco install strawberryperl --version 5.38.0 --install-arguments="INSTALLDIR=""C:\Strawberry538"""
#  - appveyor-retry choco upgrade strawberryperl --version 5.38.0
  - refreshenv
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - path
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  
  #- cpanm --installdeps --notest PDL
  #- ppm set repository BDV_PPM http://biodiverse.unsw.edu.au/downloads/ppm
  #- ppm install --location http://biodiverse.unsw.edu.au/downloads/ppm PDL
  #- perl -MPDL -E"say 1"  #  check installation
  #- cpanm --notest --no-man-pages PDL
  
  #  aliens should be cached now
  - cpanm --quiet --notest Module::Compile
    
  - cpanm --quiet --notest Alien::Build
  
  - cpanm -v --notest Alien::sqlite
  - cpanm -v --notest Alien::geos::af
  - cpanm -v Alien::libtiff
  - cpanm -v Alien::proj
  
#  - set ALIEN_GDAL_CONFIG_ARGS=--without-spatialite --without-gnm --without-qhull
  - cpanm -v Alien::gdal

  - cpanm --notest --installdeps .
  - cpanm --installdeps .


build_script:
  - prove -l
#  - perl -e "1"

