branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\Strawberry
  #- C:\Strawberry -> appveyor.yml

install:
  - if not exist "C:\strawberry" appveyor-retry choco install strawberryperl --version 5.30.2.1
  #- appveyor-retry choco upgrade strawberryperl --version 5.28.1.1
  - set ST=C:\Strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - path
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  
  #- cpanm --installdeps --notest PDL
  #- ppm set repository BDV_PPM http://biodiverse.unsw.edu.au/downloads/ppm
  #- ppm install --location http://biodiverse.unsw.edu.au/downloads/ppm PDL
  #- perl -MPDL -E"say 1"  #  check installation
  #- cpanm --notest --no-man-pages PDL
  
  #  aliens should be cached now
  - cpanm --quiet --notest Module::Compile
    
  - cpanm --quiet --notest Alien::Build
  
  - cpanm -v --notest Alien::sqlite
  - cpanm -v --notest Alien::geos::af
  - cpanm -v Alien::libtiff
  - cpanm -v Alien::proj
  
  - set ALIEN_GDAL_CONFIG_ARGS=--without-spatialite --without-gnm --without-qhull
  - cpanm -v Alien::gdal
  
  - cpanm --notest --installdeps .
  - cpanm --installdeps .


build_script:
  - prove -l
  #- perl -e "1"

