name: linux_de_locale

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL_MOD_DIR: /home/runner/perl5/lib/perl5
  #PERL5LIB: /home/runner/perl5/lib/perl5
  #PERL_LOCAL_LIB_ROOT: /home/runner/perl5
  #PERL_MB_OPT: --install_base /home/runner/perl5
  #PERL_MM_OPT: INSTALL_BASE=/home/runner/perl5
  #LC_NUMERIC: de_DE.iso88591
  #LC_CTYPE: de_DE.iso88591

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'

      - name: update apt get
        run: |
          sudo apt-get update

      - name: gdal stack
        run: |
          sudo apt-get --yes install libgdal-dev

      - name: cmake
        run: |
          sudo apt-get --yes install cmake

      - name: Locale check
        run: |
          locale -a
          #sudo locale-gen de_DE.iso88591
          #sudo update-locale de_DE.iso88591
          sudo locale-gen de_DE
          sudo update-locale de_DE

      - name: Locale check 2
        run: |
          locale -a
          echo Current locale:
          locale

      - name: perl -V
        run: perl -V

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          echo '20220920' >> perlversion.txt
          ls -l perlversion.txt

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install Dynamic Dependencies
        run: |
          which -a cpanm
          which -a perl
          cpanm --notest local::lib
          echo $(perl -Mlocal::lib=${HOME}/perl5)
          eval "$(perl -Mlocal::lib=${HOME}/perl5)"
          #eval $(perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib)
          cpanm --installdeps FFI::Platypus
          cpanm --notest FFI::Platypus
          #cpanm --notest FFI::Platypus::Declare
          cpanm --notest Alien::Build  
          cpanm --installdeps --notest Alien::sqlite
          cpanm -v Alien::sqlite
          cpanm --installdeps --notest Alien::libtiff
          cpanm -v Alien::libtiff
          cpanm --installdeps --notest Alien::geos::af
          cpanm -v Alien::geos::af
          cpanm --installdeps --notest Alien::proj
          cpanm -v Alien::proj
          cpanm --installdeps --notest Alien::gdal
          cpanm -v Alien::gdal
          cpanm --notest --installdeps --no-man-pages PDL
          cpanm --notest --no-man-pages PDL
          #cpanm --notest Task::Biodiverse::NoGUI
          #cpanm --notest Test2::Suite
          #cpanm --notest Test2::Harness
          cpanm --installdeps .
          
      - name: Gtk stuff
        run: |
          sudo apt-get install libpango1.0-dev libgtk2.0-dev
          echo $(perl -Mlocal::lib=${HOME}/perl5)
          eval "$(perl -Mlocal::lib=${HOME}/perl5)"
          cpanm --notest Pango
          cpanm --notest Gtk2
      
      - name: Run matrix tests
        run: |
          echo $(perl -Mlocal::lib=${HOME}/perl5)
          eval "$(perl -Mlocal::lib=${HOME}/perl5)"
          sudo update-locale de_DE
          export LC_NUMERIC=de_DE.iso88591
          export LC_CTYPE=de_DE.iso88591
          locale
          perl -MPOSIX -E'say join " ", POSIX::strtod 3.14'
          export BD_TEST_GUI=1
          prove -v t/25-Matrix.t


      - name: Run Tests
        run: |
          echo $(perl -Mlocal::lib=${HOME}/perl5)
          eval "$(perl -Mlocal::lib=${HOME}/perl5)"
          sudo update-locale de_DE
          export LC_NUMERIC=de_DE.iso88591
          export LC_CTYPE=de_DE.iso88591
          locale
          perl -MPOSIX -E'say join " ", POSIX::strtod 3.14'          
          prove -l -j4
          #yath -I t/lib -PBiodiverse::TestHelpers -PBiodiverse::BaseData -PGeo::GDAL::FFI -PPDL -D test -j 4
