name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: /Users/runner/perl5/lib/perl5
  PERL_LOCAL_LIB_ROOT: /Users/runner/perl5
  PERL_MB_OPT: --install_base /Users/runner/perl5
  PERL_MM_OPT: INSTALL_BASE=/Users/runner/perl5

jobs:
  perl:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl
        run: |
          brew install perl
          echo "/Users/runner/perl5/bin" >> $GITHUB_PATH
          mkdir -p ~/bin
          cd ~/bin
          curl -L https://cpanmin.us/ -o cpanm
          chmod +x cpanm
          echo "~/bin" >> $GITHUB_PATH
          which perl
          which cpanm

      #  some painful steps here that will hopefully be backed out at some point
      - name: Install GDAL and its deps
        run: |
          brew update
          brew unlink pkg-config@0.29.2
          brew install pkgconf
          brew link --overwrite pkgconf
          brew install gdal
          # brew install --force --overwrite gdal
        
      - name: perl -V
        run: perl -V

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          echo '20241125' >> perlversion.txt
          ls -l perlversion.txt

      - name: Cache CPAN modules
        uses: actions/cache@v4
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install Dynamic Dependencies
        run: |
          cpanm --notest --installdeps .
      
      - name: Run Tests
        run: prove -l -j4
        