name: Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
#  PERL5LIB: c:\cx\lib\perl5
#  PERL_LOCAL_LIB_ROOT: c:/cx
#  PERL_MB_OPT: --install_base C:/cx
#  PERL_MM_OPT: INSTALL_BASE=C:/cx
  #ALIEN_BUILD_PRELOAD: Fetch::Cache
  AUTOMATED_TESTING: 1

jobs:
  perl:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
          distribution: strawberry

      - name: perl -V
        run: perl -V
        
      - name: Prepare for CPAN cache
        run: |
          perl -V > perlversion.txt
          echo "20240906b" >> perlversion.txt
          dir perlversion.txt

      - name: Cache CPAN modules
        uses: actions/cache@v4
        with:
          path: D:\a\biodiverse\biodiverse\local
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      #  Was giving grief.  Hurts not to leave here.
      - name: Install dependencies Sereal
        run: |
          #echo $env:PATH
          echo $env:PERL5LIB
          cpanm --installdeps Sereal::Decoder
          cpanm Sereal::Decoder
          cpanm --installdeps Sereal::Encoder
          cpanm Sereal::Encoder
          cpanm Sereal

      - name: Install dependencies Alien::MSYS
        run: |
          cpanm Alien::Build::Plugin::Fetch::Cache
          cpanm --notest Alien::MSYS

      - name: Install dependencies Alien::sqlite
        run: |
          echo $env:PATH
          cpanm --notest --installdeps Alien::sqlite
          cpanm -v Alien::sqlite

      - name: Install dependencies Alien::proj
        run: |
          #cpanm -v --notest https://github.com/shawnlaffan/perl-alien-proj.git
          cpanm --notest --installdeps Alien::proj
          cpanm -v --notest Alien::proj

      - name: Install dependencies Alien::geos::af
        run: |
          cpanm --notest --installdeps Alien::geos::af
          cpanm -v Alien::geos::af

      - name: Install dependencies Alien::gdal
        run: |
          cpanm --notest --installdeps Alien::gdal
          echo "ALIEN_GDAL_CONFIG_ARGS=--with-hide_internal_symbols" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          #  qhull issues on gdal 3.5, maybe fixed in 3.6
          # $env:ALIEN_GDAL_CONFIG_ARGS = "--with-hide-internal-symbols=yes --without-gnm --without-qhull"
          Get-PSDrive C | Select-Object Used,Free
          #  clunky path override
          #  $env:PATH = "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;$env:PATH"
          cpanm -v Alien::gdal
          Get-PSDrive C | Select-Object Used,Free
          
      - name: Install task deps
        run: |
          #cpanm --notest Task::Biodiverse::NoGUI
          cpanm --notest --no-man-pages PDL
          cpanm --notest --installdeps .
          cpanm --installdeps .
  
      # Runs a set of commands using the runners shell
      - name: Run tests
        run: |
          prove -l 
          